<<<<<<< HEAD
# Generated by Django 5.0 on 2026-03-06 22:39
=======
# Generated by Django 6.0.2 on 2026-03-06 22:40
>>>>>>> 455c6d1da41c4ac7f72679fd9b358835bec47e13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('last_ping', models.DateTimeField(auto_now=True)),
                ('battery_level', models.IntegerField(default=100)),
                ('parking_spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingspot')),
            ],
        ),
    ]
