<<<<<<< HEAD
# Generated by Django 5.0 on 2026-03-06 22:39
=======
# Generated by Django 6.0.2 on 2026-03-06 22:40
>>>>>>> 455c6d1da41c4ac7f72679fd9b358835bec47e13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
<<<<<<< HEAD
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
=======
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parking_status', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect')], default='correct', max_length=20)),
>>>>>>> 455c6d1da41c4ac7f72679fd9b358835bec47e13
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=20)),
                ('road_name', models.CharField(max_length=200)),
                ('zone', models.CharField(max_length=100)),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
