<<<<<<< HEAD
# Generated by Django 5.0 on 2026-03-06 22:39
=======
# Generated by Django 6.0.2 on 2026-03-06 22:40
>>>>>>> 455c6d1da41c4ac7f72679fd9b358835bec47e13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='parking_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingspot'),
        ),
    ]
