# Generated by Django 6.0.2 on 2026-03-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('average_parking_time', models.FloatField(default=0.0)),
                ('occupancy_rate', models.FloatField(default=0.0)),
                ('peak_hours', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Analytics',
            },
        ),
    ]
